---
- hosts: openshift
  vars:
    package: vim, telnet, tree, nmap, git, net-tools, bind-utils, bind, bridge-utils, bash-completion, docker
  tasks:

    - name: Install "{{ package }}"
      yum:
        name: '{{ package }}'
        state: latest

    - name: install custom fact
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: 0755

    - name: create ansible user
      user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa


    - name: ansible authorized keys
      template:
        src: authorized_keys.j2
        dest: /home/ansible/.ssh/authorized_keys
        mode: 0600

    - name: set sudoers
      template:
        src: sudoers.j2
        dest: /etc/sudoers
        mode: 0440

    - name: set sshd
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: 0600
      register: sshd

    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when: sshd.changed

    - name: manage docker config
      template:
        src: docker.j2
        dest: /etc/sysconfig/docker
        mode: 0644

    - name: manage docker storage
      template:
        src: docker-storage-setup.j2
        dest: /etc/sysconfig/docker-storage-setup
        mode: 0644
